name: dnsbl-client # you probably want to 'snapcraft register <name>'
version: '1.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: simple interface to lookup blacklists results
description: |
  dnsbl-client queries DNS Blacklists for listings. Currently this only does IP lookups, but the next version will handle domains.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  dnsbl-client:
    source: .
    plugin: nil
    override-build: |
      /usr/bin/gem build dnsbl-client.gemspec
      /usr/bin/gem install dnsbl-client-*.gem
    build-packages: [ruby]
    stage-packages: [ruby]

apps:
  dnsbl-client:
    environment:
      RUBYLIB: $SNAP/usr/lib/ruby/2.7.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/2.7.0
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP
    command: ruby $SNAP/bin/dnsbl-client
